apiVersion: clusterinventory.kyma-project.io/v1beta1
kind: Cluster
metadata:
  labels:
    kyma-project.io/instance-id: instance-id
    kyma-project.io/runtime-id: runtime-id
    kyma-project.io/broker-plan-id:  plan-id
    kyma-project.io/broker-plan-name: plan-name
    kyma-project.io/global-account-id: global-account-id
    kyma-project.io/subaccount-id: subAccount-id
    kyma-project.io/shoot-name: shoot-name
    "kyma-project.io/region": region
    operator.kyma-project.io/kyma-name: kymaName
  name: cluster-sample
spec:
  core:
    shootName: "shoot-name"
  adminKubeconfig:
    secretName: "secret-name"
