---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: component-reconcilers-connectivity-proxy
  namespace:  {{ .Release.Namespace }}
  labels:
    app: component-reconcilers-connectivity-proxy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-connectivity-proxy
  namespace:  {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: component-reconcilers-connectivity-proxy
  namespace:  {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: component-reconcilers-connectivity-proxy
    namespace:  default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: component-reconcilers-connectivity-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: component-reconcilers-connectivity-proxy-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: component-reconcilers-connectivity-proxy-secrets
  namespace: kcp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: component-reconcilers-connectivity-proxy-secrets
subjects:
  - kind: ServiceAccount
    name: component-reconcilers-connectivity-proxy
    namespace: kcp-system