{{- if .Values.global.shootSpecDump.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-prov-shoot-spec-storage
  namespace: kcp-system
spec:
  storageClassName: kim-shoot-tests
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
{{- end }}