name: Run unit tests
on:
  push:
    branches: [ main ]
    paths:
      - 'components/provisioner/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'components/provisioner/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        run: make -C components/provisioner verify
